### ISSUE TITLE
Add support for multiple Y values

### ISSUE THREAD

**Issue by smeijer** [justinvdm/xy#1]
Would be nice if we could combine multiple values in a single chart.

For example; to compare the `used heap` with the `total heap`. Or to plot the `cpu` usage of two (or more) instances on the same chart.

**Comment by justinvdm** [comment]
Thank you for the message! I'm very sorry I am only seeing this after two years, somehow I missed it.

No idea whether this would still be valuable for you still, but as it turns out this feature is supported! (most likely I added that support some time after your message):

```bash
while true; do echo `date +%s` `uptime | cut -d':' -f4-` \
  | jq -cs '. as [$xs, $m1, $m5, $m15] | ($xs * 1000) as $x | [{k: "1m", x: $x, y: $m1}, {k: "5m", x: $x, y: $m5}, {k: "15m", x: $x, y: $m15}][]'; sleep 1; done \
  | xy -k k -T '%S' -S 1m -c red -S 5m -c green -S 15m -c blue
```
